---
- name: resolve platform specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release | default(ansible_distribution_major_version) }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
      paths:
        - '{{ role_path }}/vars'

- include_tasks: |-
    {% if terraform_installer is undefined %}
    {{ (ansible_os_family == "Windows") | ternary("win_tgz", "tgz") }}
    {% else %}
    {{ terraform_installer }}
    {% endif %}.yml