---
- name: check for installation
  become: yes
  stat:
    path: '{{ terraform_binary_dir }}'
  changed_when: False
  register: terraform_binary
- when: not terraform_binary.stat.exists
  block:
    - name: download terraform...
      become: yes
      become_user: root
      get_url:
        url: '{{ terraform_url }}'
        dest: /tmp/{{ terraform_zip }}
        checksum: '{{ terraform_checksum }}'
        mode: 0644
    - name: create directory for terraform
      become: yes
      become_user: root
      file:
        path: '{{ terraform_binary_dir }}'
        state: directory
        mode: 0755
    - name: unarchive terraform...
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ terraform_zip }}
        dest: '{{ terraform_binary_dir }}'
        creates: '{{ terraform_binary_dir }}/terraform'
  always:
    - name: cleanup...
      become: yes
      become_user: root
      file:
        path: /tmp/{{ terraform_zip }}
        state: absent
- name: link terraform
  become: yes
  become_user: root
  file:
    src: '{{ terraform_binary_dir }}/terraform'
    dest: '{{ terraform_install_dir }}/terraform'
    state: link
    force: '{{ terraform_force_install }}'
