---
- name: check for installation
  become: '{{ terraform_privilege_escalate }}'
  become_user: root
  win_stat:
    path: '{{ terraform_binary_dir }}'
  changed_when: False
  register: terraform_binary
- when: not terraform_binary.stat.exists
  block:
    - name: downloading {{ terraform_url }}...
      become: '{{ terraform_privilege_escalate }}'
      become_user: root
      win_get_url:
        url: '{{ terraform_url }}'
        dest: '{{ terraform_temp_exe }}'
        checksum: '{{ terraform_checksum }}'
        mode: 0644
    - name: mkdir {{ terraform_binary_dir }}
      become: '{{ terraform_privilege_escalate }}'
      become_user: root
      win_file:
        path: '{{ terraform_binary_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ terraform_temp_exe }} to {{ terraform_binary_dir }}
      become: '{{ terraform_privilege_escalate }}'
      become_user: root
      win_unzip:
        remote_src: yes
        src: '{{ terraform_temp_exe }}'
        dest: '{{ terraform_binary_dir }}'
        creates: '{{ terraform_installed_exe }}'
  always:
    - name: rm {{ terraform_temp_exe }}
      become: '{{ terraform_privilege_escalate }}'
      become_user: root
      win_file:
        path: '{{ terraform_temp_exe }}'
        state: absent
- name: export {{ terraform_installed_exe }} to PATH
  debug:
    msg: '{{ terraform_installed_exe }}'
